/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package macquarie.interview;

import macquarie.interview.email.Email;
import macquarie.interview.email.EmailSender;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Supplier;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        FInterface f = s -> {
            String s2 = s.toLowerCase();
            System.out.println(s2);
        };
        f.doSomething("SOMETHING IN CAPS");

        Consumer<String> stringFunction = s -> {
            String s2 = s.toUpperCase();
            System.out.println(s2);
        };

        stringFunction.accept("consumer");

        TriFunction<Integer, Integer, Integer, String> tri = (integer, integer2, integer3) -> String.valueOf(integer) + integer2 + integer3;

        tri.apply(1, 2, 3);

        EmailSender emailSender = new EmailSender(false);
        Email email = emailSender.getEmailSender().apply();
        System.out.println(email);
        Supplier<String> someMethod = emailSender::someMethod;
        System.out.println(someMethod.get());
        NoArgFunction<String> fss = () -> "sdsdsd";

        List<Integer> list = new ArrayList<>(Arrays.asList(1,2,3,4,5,6));
        list.add(22);
        System.out.println(list);
        List<Integer> list2 = new ArrayList<>(List.of(1,2,3,4,5));
        list2.add(22);
        System.out.println(list2);
        List<Integer> list3 = new ArrayList<>(List.copyOf(list2));
        list3.add(22);
        System.out.println(list3);
    }
}
